### ISSUE TITLE
swpacket.cpp compiling issue

### ISSUE THREAD

**Issue by adechassey** [panStamp/swap#5]
Hi,
Weird error here : 
C:\Users\XXX\Documents\Arduino\libraries\SWAP\swpacket.cpp: In member function 'bool SWPACKET::send()':
C:\Users\XXX\Documents\Arduino\libraries\SWAP\swpacket.cpp:168:26: error: 'class PANSTAMP' has no member named 'sendData'
   while(!(res = panstamp.sendData(ccPacket)) && i>1)
                          ^

Fresh install : 
- Arduino 1.6.5
- Installed panstamp AVR core (by board manager)
- Installed Libraries by libraries manager
  (- Included swap by "sketch>include library...")

**Comment by dberenguer** [comment]
What application are you trying to compile?

Daniel Berenguer
http://www.panstamp.com

**Comment by adechassey** [comment]
Hello it was a homemade sketch using pressure sensors.
Problem solved by using :
Arduino ide 1.6.5
- Boards : Arduino AVR boards 1.6.5
- Boards :Panstamp AVR 1.5.4
- Lib : SWAP 1.0.5
